version: '3.9'

services:
  consul:
    image: consul:1.9.5
    container_name: consul
    ports:
      - "8005:8500"  # Consul UI
      - "8700:8700/udp"
    command: consul agent -dev -client=0.0.0.0
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - consul
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - redis
      - consul
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - backend

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - consul
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - backend

  frontend:
    build: ./Sales-Application-Frontend
    ports:
      - "4200:80"
    depends_on:
      - auth-service
      - user-service
      - order-service
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
