version: '3.9'

services:
  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - redis
    networks:
      - backend

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - redis
    networks:
      - backend

  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - backend
  frontend:
    build: ./Sales-Application-Frontend
    ports:
      - "4200:80"
    depends_on:
      - auth-service
      - user-service
      - order-service

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    driver: overlay
